language: generic
sudo: false

cache:
    directories:
        - $HOME/.ghc
        - $HOME/.cabal

addons:
    apt:
        sources:
            - hvr-ghc
        packages:
            - cabal-install-1.24
            - ghc-8.0.2

before_install:
    - export PATH=$HOME/.cabal/bin:/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH

script:
    - cabal install --only-dependencies --enable-tests
    - cabal build
